;custom_proxy_group=IP--🚀 节点选择`select`Home|搬瓦工|8TB|25TB`[]DIRECT`[]IP--📡 ISP-1️⃣`[]IP--📡 ISP-2️⃣
ruleset=👽 AI,https://raw.githubusercontent.com/callejoncho/Clash/refs/heads/main/AI.list
ruleset=StockX&Goat,https://raw.githubusercontent.com/callejoncho/Clash/refs/heads/main/StokcX-Alias.list
ruleset=server,https://raw.githubusercontent.com/callejoncho/Clash/refs/heads/main/server.list
ruleset=AdsPower,https://raw.githubusercontent.com/callejoncho/Clash/refs/heads/main/ISPs.list
ruleset=Footsites,https://raw.githubusercontent.com/callejoncho/Clash/refs/heads/main/Footsites.list
ruleset=FinishLine,https://raw.githubusercontent.com/callejoncho/Clash/refs/heads/main/FNL.list
ruleset=🐦 Arcteryx,https://raw.githubusercontent.com/callejoncho/Clash/refs/heads/main/Arcteryx.list
ruleset=Dicks,https://raw.githubusercontent.com/callejoncho/Clash/refs/heads/main/Dicks.list
ruleset=Nike,https://raw.githubusercontent.com/callejoncho/Clash/refs/heads/main/nike.list
ruleset=TikTok,https://raw.githubusercontent.com/callejoncho/Clash/refs/heads/main/TikTok.list
ruleset=mlx,https://raw.githubusercontent.com/callejoncho/Clash/refs/heads/main/mlx.list


ruleset=🌍 国外,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🌍 国外,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🌍 国外,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
;ruleset=🌍 国外,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/Proxy.list
;ruleset=🌍 国外,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ProxyGFWlist.list
;ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/callejoncho/Clash/refs/heads/main/DIRECT.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL
;ruleset=➡️ 国内,[]FINAL




;2节点组


custom_proxy_group=IP--🚀 节点选择`select`.*`[]DIRECT
custom_proxy_group=🌍 国外`select`[]IP--🚀 节点选择`[]DIRECT`.*
custom_proxy_group=👽 AI`select`select`.*`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]IP--🚀 节点选择`[]DIRECT
custom_proxy_group=🐦 Arcteryx`select`[]IP--🚀 节点选择`[]DIRECT`.*
custom_proxy_group=StockX&Goat`[]IP--🚀 节点选择`[]DIRECT`.*
custom_proxy_group=server`select`[]IP--🚀 节点选择`[]DIRECT`.*
custom_proxy_group=AdsPower`select`[]IP--🚀 节点选择`[]DIRECT`.*
custom_proxy_group=Footsites`select`[]IP--🚀 节点选择`[]DIRECT`.*
custom_proxy_group=FinishLine`select`[]IP--🚀 节点选择`[]DIRECT`.*
custom_proxy_group=Dicks`select`[]IP--🚀 节点选择`[]DIRECT`.*
custom_proxy_group=Nike`select`[]IP--🚀 节点选择`[]DIRECT`.*
custom_proxy_group=TikTok`select`[]IP--🚀 节点选择`[]DIRECT`.*
custom_proxy_group=mlx`select`[]IP--🚀 节点选择`[]DIRECT`.*







;4、启用规则集
enable_rule_generator=true
overwrite_original_rules=true
