;custom_proxy_group=IP--🚀 节点选择`select`Home|搬瓦工|8TB|25TB`[]DIRECT`[]IP--📡 ISP-1️⃣`[]IP--📡 ISP-2️⃣`
ruleset=🌍 国外,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🌍 国外,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🌍 国外,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
;ruleset=🌍 国外,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/Proxy.list
;ruleset=🌍 国外,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ProxyGFWlist.list
;ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/callejoncho/Clash/refs/heads/main/DIRECT.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=mlx,https://raw.githubusercontent.com/callejoncho/Clash/refs/heads/main/mlx.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL
;ruleset=➡️ 国内,[]FINAL

;custom_proxy_group=IP--🚀 节点选择`select`Home|搬瓦工|8TB|25TB`[]IP--📡 ISP-1️⃣`[]IP--📡 ISP-2️⃣`[]DIRECT
custom_proxy_group=IP--🚀 节点选择`select`.*`[]DIRECT
custom_proxy_group=mlx`select`[]DIRECT
;custom_proxy_group=IP--🚀 节点选择`select`Home|搬瓦工|8TB|25TB`[]DIRECT`[]IP--📡 ISP-1️⃣`[]IP--📡 ISP-2️⃣
;custom_proxy_group=IP--🚀 节点选择`select`[]IP--✈️ 自建节点- Group 1️⃣

;2、策略组（域名组-节点组）

;custom_proxy_group=📘 GitHub`select`[]IP--🚀 节点选择`[]DIRECT`[]IP--✈️ 自建节点- Group 1️⃣`
;custom_proxy_group=🙋 Telegram`select`[]IP--🚀 节点选择`[]DIRECT`[]IP--✈️ 自建节点- Group 1️⃣`

custom_proxy_group=🌍 国外`select`[]IP--🚀 节点选择`[]DIRECT
;custom_proxy_group=➡️ 国内`select`[]DIRECT`[]IP--🚀 节点选择
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]IP--🚀 节点选择`[]DIRECT

;3、节点组
;custom_proxy_group=IP--✈️ 自建节点- Group 1️⃣`select`(Home|搬瓦工|8TB|25TB)
;custom_proxy_group=IP--✈️ 自建节点- Group 2️⃣`select`(Home|搬瓦工|8TB|25TB)
;custom_proxy_group=IP--🚀 节点选择`select`.*`[]DIRECT
;custom_proxy_group=IP--♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=IP--🇭🇰 香港节点`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=IP--📡 ISP-1️⃣`select`(THE-PLAN|68_|goodip|niceip|hostdzire)
;custom_proxy_group=IP--📡 ISP-2️⃣`select`(THE-PLAN|68_|goodip|niceip|hostdzire)





;4、启用规则集
enable_rule_generator=true
overwrite_original_rules=true
